### ISSUE TITLE
About reasonable limits

### ISSUE THREAD

**Issue by Yamato-01** [christsa/dgrasp#1]
Great work! I want to know how to restrict the joints within reasonable limits in your project?

**Comment by christsa** [comment]
Thanks!

We looked at the distribution of poses in the DexYCB dataset and extracted the limits of each joint. We then heuristically added some slack to increase these joint limits, because the dataset does not cover the full range of possible hand motions.

**Comment by Yamato-01** [comment]
Does it means you define local coordinate system for MANO's joints? Could you share the limits data of each joint? Thanks a lot!

**Comment by christsa** [comment]
Yes, exactly, each joint rotation has its own limits.

You can find the joint limits we used in the urdf file [here](https://github.com/christsa/dgrasp/blob/main/rsc/mano/mano_mean.urdf).
