### ISSUE TITLE
About changing the environment setting s

### ISSUE THREAD

**Issue by YiLin32Wang** [christsa/dgrasp#12]
Hi,

I'm trying to adapt this code framework to my own problem setting with requirements of changing the environment settings such as table, object amounts and reward functions,
Just wanna make sure that In this case, am I supposed to code my own environment in Environment.hpp and regenerate the .so files in the bin folder to generate my own environment by running python setup.py develop under raisimGymTorch folder ?

Thanks!

**Comment by YiLin32Wang** [comment]
Hi,

I'm trying to adapt this code framework to my own problem setting with requirements of changing the environment settings such as table, object amounts, reward functions and changing hand to human body.

Just wanna make sure that In this case, am I supposed to code my own environment in `Environment.hpp` and regenerate the `.so` files in the `bin` folder to generate my own environment by running `python setup.py develop` under `raisimGymTorch` folder ?

Thanks!

**Comment by christsa** [comment]
Hi,

Yes that is correct. You also need to adapt the runner.py file in the same folder.
Let me know if you have any more questions.

Best,
Sammy
