### ISSUE TITLE
A question about .pkl

### ISSUE THREAD

**Issue by xiaohao9999** [christsa/dgrasp#17]
Hi,

I noticed you have the following file.

![image](https://github.com/christsa/dgrasp/assets/146507142/86e28254-3340-4886-b4b9-cf36bba7a0c7)

and you use them in your code
`dict_labels=joblib.load("raisimGymTorch/data/dexycb_train_labels.pkl")`

Can you kindly tell me how you obtained these pkl files?

**Comment by xiaohao9999** [comment]
```
IDX_TO_OBJ = {
    1: ['002_master_chef_can',0.414, 0, [0.051,0.139,0.0]],
    2: ['003_cracker_box', 0.453, 1, [0.06, 0.158, 0.21]],
    3: ['004_sugar_box', 0.514, 1, [0.038, 0.089, 0.175]],
    4: ['005_tomato_soup_can', 0.349, 0, [0.033, 0.101,0.0]],
    5: ['006_mustard_bottle', 0.431,2, [0.0,0.0,0.0]],
    6: ['007_tuna_fish_can', 0.171, 0, [0.0425, 0.033,0.0]],
    7: ['008_pudding_box', 0.187, 3, [0.21, 0.089, 0.035]],
    8: ['009_gelatin_box', 0.097, 3, [0.028, 0.085, 0.073]],
    9: ['010_potted_meat_can', 0.37, 3, [0.05, 0.097, 0.089]],
    10: ['011_banana', 0.066,2, [0.028, 0.085, 0.073]],
    11: ['019_pitcher_base', 0.178,2, [0.0,0.0,0.0]],
    12: ['021_bleach_cleanser', 0.302,2, [0.0,0.0,0.0]], # not sure about weight here
    13: ['024_bowl', 0.147,2, [0.0,0.0,0.0]],
    14: ['025_mug', 0.118,2, [0.0,0.0,0.0]],
    15: ['035_power_drill', 0.895,2, [0.0,0.0,0.0]],
    16: ['036_wood_block', 0.729, 3, [0.085, 0.085, 0.2]],
    17: ['037_scissors', 0.082,2, [0.0,0.0,0.0]],
    18: ['040_large_marker', 0.01, 3, [0.009,0.121,0.0]],
    19: ['051_large_clamp', 0.125,2, [0.0,0.0,0.0]],
    20: ['052_extra_large_clamp', 0.102,2, [0.0,0.0,0.0]],
    21: ['061_foam_brick', 0.028, 1, [0.05, 0.075, 0.05]],
}

```
Hi, I also want to know what is the 2nd element of each list in the dict, i.e. the integers in the list.

**Comment by sammychristen** [comment]
Hi,

The integers in the dict refer to the following:
0 - use approximated cylinder primitive mesh
1 - use approximated box primitive mesh
2 - use decimated original mesh
3 - some special cases of boxes/cylinders had to be aligned with the coordinate system of DexYCB. 3 indicate these aligned primitive shapes

The meshes are loaded accordingly in the code [here](https://github.com/christsa/dgrasp/blob/8816d1ba80fbd95ec93142cb91695719effd05e9/raisimGymTorch/raisimGymTorch/env/envs/dgrasp/Environment.hpp#L178-L220).

About your questions for the .pkl files:
Each label in these .pkl files contain the hand pose (51) and velocities (51), object pose (6) and velocities (6), object displacement (3), vert. distance to table (3), goal position distances (63), goal pose distances (48), contact goal vector (48). You can find a [script](https://github.com/christsa/dgrasp/blob/main/raisimGymTorch/raisimGymTorch/helper/convert_label.py) that converts a grasp label from DexYCB (given in MANO PCA representation as provided [here](https://github.com/NVlabs/dex-ycb-toolkit)) or GraspTTA (pose given in axis angles, hence the hand_param can be directly used [here](https://github.com/christsa/dgrasp/blob/4c7d9f84bbcdfb58687a1ddf9e78ee2efb2396a2/raisimGymTorch/raisimGymTorch/helper/convert_label.py#L62)) into a Dgrasp label with the information mentioned above.

**Comment by xiaohao9999** [comment]
Hi, 

Thank you for your detailed explanation! I will carefully read the content you mentioned. 😀
