### ISSUE TITLE
p gains should have the same dimension as the degrees of freedom

### ISSUE THREAD

**Issue by yqj13777866390** [christsa/dgrasp#2]
Hi christsa,
Your work is very interesting and i want to reproduce your work, but I encountered some problems as follows.
This code was run with Python 3.8 on Ubuntu 20.04 and an NVIDIA GeForce RTX 1080 Ti.

below is what i obtained from the terminal:
python raisimGymTorch/env/envs/dgrasp/runner.py  -o 1 -e "grasping" -d "/log" -sd "/model" 
Configuration file: "cfg.yaml"
Experiment name: "grasping"
num envs 200
[2022:10:02:23:14:18 ArticulatedSystem.hpp:1042] p gains should have the same dimension as the degrees of freedom

python raisimGymTorch/env/envs/dgrasp/runner_motion.py -ao -e 'all_objs'  -sd 'pretrained_policies' -w 'full_6000.pt' 
Configuration file: "cfg.yaml"
Experiment name: "all_objs"
num envs 376
> /data1/yqj/human-obejct/dgrasp/raisimGymTorch/raisimGymTorch/env/envs/dgrasp/runner_motion.py(173)<module>()
-> env = mano.RaisimGymEnv(home_path + "/rsc", dump(cfg['environment'], Dumper=RoundTripDumper))
[2022:10:02:23:18:01 ArticulatedSystem.hpp:1042] p gains should have the same dimension as the degrees of freedom

Best,
Qiaojun

**Comment by christsa** [comment]
Hi Qiaojun,

I did a fresh install from scratch on Ubuntu 20.04 with python 3.8 as in your case but was not able to reproduce your error.
Did you follow [these steps](https://github.com/christsa/dgrasp/blob/main/docs/INSTALLATION.md) for installation?
If so, to help me reproduce, can you add the following to [this line](https://github.com/christsa/dgrasp/blob/main/raisimGymTorch/raisimGymTorch/env/envs/dgrasp/Environment.hpp#L85) and report the output:
`std::cout << "dim " << gvDim_ << std::endl;`

Thanks,
Sammy

**Comment by yqj13777866390** [comment]
Hi Sammy,
Thank you for your help and patience，this error happens when i use different versions of the RaiSim physics simulation for building and linking.
The appropriate version of RaiSim physics simulation is 1.1.0（The official RaiSim repository is 1.1.5 ）
Best,
Qiaojun

**Comment by christsa** [comment]
Hi Qiaojun,

Yes, I haven't tested D-Grasp with newer versions of RaiSim. The easiest is just to install RaiSim via the D-Grasp repository.
Do I understand you correctly that it is working now? 

Best,
Sammy

**Comment by yqj13777866390** [comment]
Hi Sammy,

Thank you for your help, it is working now and RaiSim physics simulation is 1.1.0.

Best,
Qiaojun
