### ISSUE TITLE
No png file

### ISSUE THREAD

**Issue by zihos** [christsa/dgrasp#3]
Dear author,
I tried to run the demo but there were some errors.
I think that the errors occurs due to there's no such png files in the git repository.
![image](https://user-images.githubusercontent.com/46514182/201722994-b950115f-b61c-4e73-b1a2-d940be4e9b7e.png)
Where can I get those png files?
Thank you.
Best regards,
Jiho Park.

**Comment by christsa** [comment]
Dear Jiho,

Thanks for the pointer!
I have added the png files to the latest commit.

Can you confirm it's working now?

Best,
Sammy
