### ISSUE TITLE
Having trouble with visualization using raisimUnity

### ISSUE THREAD

**Issue by gmindflow** [christsa/dgrasp#8]
Hello, 

I am having some trouble with visualization using raisimUnity.
I have made my virtual environment on Ubuntu 22.04 and python 3.8 on it.
And I have upgraded my nvidia driver to 525.

In the installing process, everything worked well except one thing.
When I ran the `sudo apt install vulkan-utils` command, it did not run and just gave me an output saying the package does not exist.
I looked it up and seemed like this vulkan-utils package has been included in vulkan-tools which ran successfully.

I have noticed you have done this project on Ubuntu 20.04. Would this difference might be causing problems with visualization?
This is the error I got on raisimUnity while running the code. (The code runs okay by the way)
![unnamed](https://user-images.githubusercontent.com/102780751/220027804-04772882-a2d2-46d6-a6c4-c19b915f730d.png)

**Comment by christsa** [comment]
Hi,

This seems to be an issue related to vulkan and not RaiSim. It looks like a linking problem.

Can you try the following fix (source: [link](https://github.com/sn4k3/UVtools/discussions/342)):
`sudo ln -s /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so` 


Thanks,
Sammy

**Comment by gmindflow** [comment]
Thank you so much for your fast reply Sammy.
Really appreciate it!

Also what you suggested me to try worked out perfectly!
Got it solved right away.

Thank you a lot, take care.
